### ISSUE TITLE
This doesnt quite seem so universal

### ISSUE THREAD

**Issue by SIMULATAN** [Si1kn/LunarToTecknixProfile#1]
https://github.com/Si1kn/LunarToTecknixProfile/blob/6f3ea8917a40d53071db00e14a766347b5b4d037/src/main/java/io/github/si1kn/lunartotecknixconverter/LunarToTecknixConverter.java#L14

fix lol

**Comment by Si1kn** [comment]
no

**Comment by SIMULATAN** [comment]
https://github.com/Si1kn/LunarToTecknixProfile/commit/ddd0b52fec7e19a1533afab5ed935f1e658d261e this looks like a **yes**
